import type { Metadata } from "next";

export const homepageMetadata: Metadata = {
  title: "Luxury Real Estate Consulting NCR | Strategic Property Investment Advisory | Celeste Abode",
  description: "Premium real estate consulting in Noida, Gurugram & Delhi NCR. Data-driven property investment advisory with RERA compliance. Expert guidance for luxury apartments.",
  keywords: [
    // Primary Keywords
    "luxury real estate consulting NCR",
    "strategic property investment advisory",
    "data-driven real estate consulting",
    "RERA compliant property advisory",
    "property investment consultant NCR",
    
    // Location-based Keywords
    "real estate consultant Noida",
    "property advisor Gurugram",
    "luxury property consultant Delhi NCR",
    "Yamuna Expressway property investment",
    "Greater Noida real estate advisor",
    "Noida Expressway property consultant",
    "Gurugram property investment advisory",
    "Delhi NCR real estate consulting",
    "Ghaziabad property advisor",
    
    // Service-based Keywords
    "bespoke lifestyle curation",
    "investment security NCR",
    "property ROI strategy",
    "signature residences NCR",
    "high-value property investment",
    "AI-powered property intelligence",
    "luxury apartment consultant",
    "villa investment advisory",
    "ready to move property NCR",
    "pre-launch property investment",
    
    // NRI & Specialized Services
    "NRI property services NCR",
    "global Indian property investment",
    "remote property management",
    "end-to-end transaction security",
    "legal property verification NCR",
    
    // Market-specific
    "Jewar Airport property investment",
    "Noida Sector 62 property",
    "luxury real estate NCR",
    "premium property advisory India",
    "real estate market intelligence",
    
    // Location-Based Keywords - Delhi NCR
    "luxury real estate in Delhi NCR",
    "premium apartments in Delhi NCR",
    "investment property Delhi NCR",
    "buy flat Delhi NCR",
    "real estate consultant Delhi NCR",
    "affordable flats in Noida NCR",
    "budget flats Delhi NCR",
    "high-end luxury flats Delhi NCR",
    "luxury 4 BHK apartment Delhi NCR",
    "real estate for NRIs Delhi NCR",
    "best residential projects in Noida & Greater Noida",
    
    // Location-Based Keywords - Noida
    "flats for sale in Noida",
    "2 BHK flat Noida",
    "3 BHK flat Noida",
    "4 BHK flat Noida",
    "apartments in Noida",
    "ready-to-move flats Noida",
    "new projects Noida",
    "luxury apartments Noida",
    "Noida real estate investment",
    "properties near Noida metro",
    "properties near Noida City Centre",
    "properties near Noida Expressway",
    "gated community flats in Noida",
    "buy 3 BHK flat in Noida",
    "ready to move flats for working professionals Noida",
    "apartments for families in Noida",
    "flats near Noida – Greater Noida border",
    
    // Location-Based Keywords - Greater Noida
    "flats for sale in Greater Noida",
    "apartments in Greater Noida",
    "2 BHK flats Greater Noida",
    "3 BHK flats Greater Noida",
    "4 BHK flats Greater Noida",
    "villas in Greater Noida",
    "luxury residences Greater Noida",
    "new projects Greater Noida",
    "real estate investment Greater Noida",
    "properties near Greater Noida West",
    "properties near Techzone",
    "properties near Yamuna Expressway",
    "properties near Knowledge Park",
    "gated community flats Greater Noida",
    "flats near metro Greater Noida",
    "get 2 BHK apartment in Greater Noida",
    "premium villa Greater Noida for sale",
    "ready to move flats Greater Noida West",
    "investment property near Yamuna Expressway",
    "flats near Aqua Line",
    "flats near Metro Greater Noida",
    "villas for sale for families in Greater Noida",
    
    // Trust & Brand Reliability / Professionalism
    "trusted real estate consultant",
    "transparent property advisory",
    "reliable real estate advisory",
    "credible investment advisor",
    "data-backed guidance",
    "honest property consultancy",
    "dependable real estate partner",
    "authentic client-first service",
    "ethical real estate consulting",
    "documented transaction security",
    "RERA-compliant properties",
    "RERA compliant projects",
    "legal verification & due diligence",
    "complete paperwork support",
    "end-to-end transaction security",
    "full documentation & compliance",
    "licensed real estate experts",
    "certified real estate experts",
    "verified builder associates",
    
    // Brand Visibility & Market Positioning
    "premium real estate advisor NCR",
    "high-end property investment advisory",
    "NCR real estate experts",
    "real estate investment consultancy",
    "top real estate consultancy in Noida",
    "top real estate consultancy in NCR",
    "curated luxury projects",
    "exclusive signature residences",
    "off-market luxury properties",
    "investment-grade real estate opportunities",
    "high ROI property investments",
    "real estate market analysis & insights",
    "property investment strategies",
    "lifestyle-driven property recommendations",
    
    // High Return / Investment Focus
    "high-ROI real estate investment",
    "data-driven ROI strategy",
    "real estate investment security",
    "property yield analysis",
    "long-term capital appreciation",
    "investment portfolio optimisation",
    "property as wealth-building asset",
    "investment-grade properties",
    "investment advisory services",
    "real estate asset management",
    "future-proof property investments",
    "smart property investment planning",
    "buy-to-let properties",
    "rental income properties",
    "capital growth properties",
    
    // Documentation, Compliance & Full-Service Advisory
    "RERA verified projects",
    "legal & regulatory compliance",
    "due diligence & legal verification",
    "complete transaction support",
    "paperwork & documentation handled",
    "end-to-end purchase process",
    "from booking to registration support",
    "transparent property records",
    "verified property documentation",
    "secure investment process",
    "safe and compliant real estate deals",
    
    // Consultancy & Client-Centric / Personalized Services
    "bespoke property advisory",
    "personalised investment plans",
    "personalized investment plans",
    "lifestyle-aligned property recommendations",
    "client-first real estate consulting",
    "tailored property solutions",
    "custom real estate advisory",
    "expert property consultancy",
    "professional property advisors",
    "real estate consulting and advising",
    "full-service real estate consultancy",
    "comprehensive property guidance",
    "NRI real estate solutions",
  ],
  openGraph: {
    title: "Luxury Real Estate Consulting NCR | Strategic Property Investment Advisory | Celeste Abode",
    description: "Premium real estate consulting in Noida, Gurugram, and Delhi NCR. Data-driven property investment advisory with RERA compliance and strategic intelligence.",
    url: "https://www.celesteabode.com",
    siteName: "Celeste Abode",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "https://www.celesteabode.com/propertyhero.avif",
        width: 1200,
        height: 630,
        alt: "Celeste Abode - Luxury Real Estate Consulting in NCR",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Luxury Real Estate Consulting NCR | Celeste Abode",
    description: "Premium real estate consulting in Noida, Gurugram, and Delhi NCR. Strategic property investment advisory with data-driven intelligence.",
    images: ["https://www.celesteabode.com/propertyhero.avif"],
    creator: "@celesteabode",
  },
  alternates: {
    canonical: "https://www.celesteabode.com",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  other: {
    "geo.region": "IN-UP",
    "geo.placename": "Noida",
    "geo.position": "28.5355;77.3910",
    "ICBM": "28.5355, 77.3910",
  },
};

