// Project metadata for SEO
export interface ProjectMetadata {
  title: string;
  description: string;
  keywords: string[];
  location: string;
  developer: string;
  reraId?: string;
  price: string;
  unitTypes: string[];
  area: string;
  status: string;
  image: string;
  slug: string;
}

// Slug mapping: ID -> slug
export const projectSlugs: Record<number, string> = {
  1: "arihant-abode",
  2: "spring-elmas",
  3: "eternia-residences",
  4: "rg-pleiaddes",
  5: "irish-platinum",
  6: "elite-x",
  7: "ace-hanei",
  8: "the-brook-and-rivulet",
  9: "renox-thrive",
  10: "civitech-strings",
  11: "forest-walk-villa",
  12: "vvip",
  13: "panchsheel-greens-ii",
};

// Reverse mapping: slug -> ID
export const projectSlugToId: Record<string, number> = Object.fromEntries(
  Object.entries(projectSlugs).map(([id, slug]) => [slug, parseInt(id)])
);

export const projectMetadata: Record<number, ProjectMetadata> = {
  1: {
    slug: "arihant-abode",
    title: "Arihant Abode Sector 10 - 2 & 3 BHK Ready to Move",
    description:
      "Arihant Abode by Arihant Group in Sector 10, Greater Noida West. Ready to move 2 & 3 BHK apartments starting ₹1.02 Cr. RERA approved, prime location.",
    keywords: [
      "Arihant Abode Greater Noida",
      "Arihant Abode Sector 10",
      "Sector 10 apartments",
      "Sector 10 Greater Noida",
      "Sector 10 Greater Noida West",
      "Sector 10 properties",
      "Sector 10 flats",
      "ready to move apartments Noida",
      "ready to move Sector 10",
      "2 BHK Greater Noida",
      "2 BHK Sector 10",
      "3 BHK Greater Noida West",
      "3 BHK Sector 10",
      "Arihant Group projects",
      "Greater Noida West ready to move",
      "Greater Noida West apartments",
      "Greater Noida properties",
      "Greater Noida flats",
    ],
    location: "Sector 10, Greater Noida West",
    developer: "Arihant Group",
    reraId: "UPRERAPRJ15792",
    price: "₹1.02 Cr",
    unitTypes: ["2 BHK", "3 BHK + 2T"],
    area: "1020-1270 sq.ft.",
    status: "Ready to Move",
    image: "/arihant-abode/hero.avif",
  },
  2: {
    slug: "spring-elmas",
    title: "Spring Elmas Sector 12 - 3 & 4 BHK Luxury Apartments",
    description:
      "Spring Elmas by Spring Group in Sector 12, Greater Noida West. Luxury 3 & 4 BHK apartments starting ₹1.52 Cr. Metro connectivity, SBI approved, smart home features.",
    keywords: [
      "Spring Elmas Greater Noida",
      "Spring Elmas Sector 12",
      "Sector 12 Greater Noida",
      "Sector 12 Greater Noida West",
      "Sector 12 apartments",
      "Sector 12 properties",
      "luxury apartments Greater Noida West",
      "luxury Sector 12 apartments",
      "3 BHK Greater Noida",
      "3 BHK Sector 12",
      "4 BHK Greater Noida",
      "4 BHK Sector 12",
      "Spring Group projects",
      "metro connectivity apartments",
      "metro connected Sector 12",
      "Greater Noida West luxury",
      "Sector 12 luxury apartments",
      "Sector 12 metro connected",
      "Sector 12 3 BHK",
      "Sector 12 4 BHK",
      "Greater Noida West Sector 12",
      "Sector 12 residential projects",
      "Sector 12 smart homes",
      "Sector 12 SBI approved",
      "Greater Noida West metro",
      "Greater Noida West luxury homes",
      "Sector 12 property for sale",
      "Sector 12 real estate",
    ],
    location: "Sector 12, Greater Noida West",
    developer: "Spring Group",
    reraId: "UPRERAPRJ274689",
    price: "₹1.52 Cr",
    unitTypes: ["3 BHK + 2T", "3 BHK + 3T", "4 BHK + Servant Room"],
    area: "1385-1895 sq.ft.",
    status: "Under Construction",
    image: "/spring-elmas/hero.avif",
  },
  3: {
    slug: "eternia-residences",
    title: "Eternia Residences TechZone 4 - Ultra Premium 3 & 4 BHK",
    description:
      "Eternia Residences by Yatharth Group + NBCC in TechZone 4, Greater Noida West. Ultra premium 3 & 4 BHK apartments starting ₹1.97 Cr. Green belt facing.",
    keywords: [
      "Eternia Residences Greater Noida",
      "Eternia Residences TechZone 4",
      "TechZone 4 apartments",
      "TechZone 4 Greater Noida",
      "TechZone 4 properties",
      "TechZone 4 flats",
      "ultra premium apartments Noida",
      "ultra premium TechZone 4",
      "Yatharth Group projects",
      "NBCC projects Greater Noida",
      "NBCC TechZone 4",
      "green belt facing apartments",
      "green belt TechZone 4",
      "Greater Noida TechZone",
      "TechZone 4 luxury apartments",
      "TechZone 4 3 BHK",
      "TechZone 4 4 BHK",
      "TechZone 4 residential projects",
      "TechZone 4 new projects",
      "TechZone 4 property for sale",
      "TechZone 4 real estate",
      "Greater Noida West TechZone",
      "TechZone 4 low density",
      "TechZone 4 green belt",
      "NBCC Greater Noida",
      "TechZone 4 premium apartments",
    ],
    location: "TechZone 4, Greater Noida West",
    developer: "Yatharth Group + NBCC",
    reraId: "UPRERAAGT10206",
    price: "₹1.97 Cr",
    unitTypes: ["3 BHK", "3 BHK + Study", "4 BHK + Study"],
    area: "1932-2625 sq.ft.",
    status: "Under Construction",
    image: "/Eternia/1.avif",
  },
  4: {
    slug: "rg-pleiaddes",
    title: "RG Pleiaddes Sector 1 - Premium 3 & 4 BHK New Launch",
    description:
      "RG Pleiaddes by RG Group in Sector 1, Greater Noida West. Premium 3 & 4 BHK apartments. New launch with 6 iconic towers, 70% open green spaces, 8 acres project.",
    keywords: [
      "RG Pleiaddes Greater Noida",
      "RG Pleiaddes Sector 1",
      "Sector 1 Greater Noida",
      "Sector 1 Greater Noida West",
      "Sector 1 apartments",
      "Sector 1 properties",
      "new launch apartments Noida",
      "new launch Sector 1",
      "RG Group projects",
      "premium apartments Greater Noida West",
      "premium Sector 1 apartments",
      "Greater Noida West new launch",
      "Sector 1 new projects",
      "Sector 1 3 BHK",
      "Sector 1 4 BHK",
      "Sector 1 residential projects",
      "Sector 1 property for sale",
      "Sector 1 real estate",
      "Greater Noida West Sector 1",
      "Sector 1 green spaces",
      "Sector 1 iconic towers",
      "RG Group Sector 1",
      "Sector 1 premium homes",
    ],
    location: "Sector 1, Greater Noida West",
    developer: "RG Group",
    reraId: "UPRERAPRJ415309",
    price: "₹8,584 per sq.ft",
    unitTypes: ["3 BHK", "4 BHK"],
    area: "Premium Sizes",
    status: "New Launch",
    image: "/RG/hero.avif",
  },
  5: {
    slug: "irish-platinum",
    title: "Irish Platinum Sector 51 - 3 & 4 BHK Near Possession",
    description:
      "Irish Platinum by Irish Infrastructure in Sector 51, Greater Noida West. Premium 3 & 4 BHK apartments near possession. 11 feet ceiling, 4 balconies, earthquake resistant.",
    keywords: [
      "Irish Platinum Greater Noida",
      "Irish Platinum Sector 51",
      "Sector 51 Greater Noida",
      "Sector 51 Greater Noida West",
      "Sector 51 apartments",
      "Sector 51 properties",
      "near possession apartments",
      "near possession Sector 51",
      "Irish Infrastructure projects",
      "premium apartments Greater Noida",
      "premium Sector 51 apartments",
      "Greater Noida near possession",
      "Sector 51 near possession",
      "Sector 51 3 BHK",
      "Sector 51 4 BHK",
      "Sector 51 residential projects",
      "Sector 51 property for sale",
      "Sector 51 real estate",
      "Greater Noida West Sector 51",
      "Sector 51 ready soon",
      "Sector 51 premium homes",
      "Irish Infrastructure Sector 51",
      "Sector 51 earthquake resistant",
    ],
    location: "Sector 51, Greater Noida West",
    developer: "Irish Infrastructure",
    reraId: "UPRERAPRJ742692",
    price: "Special Rates",
    unitTypes: ["3 BHK", "4 BHK"],
    area: "1390-2550 sq.ft.",
    status: "Near Possession",
    image: "/Irish/hero.avif",
  },
  6: {
    slug: "elite-x",
    title: "Elite X Yamuna Expressway - 3 BHK Investment Opportunity",
    description:
      "Elite X by Eldeco Group in Sector 22D, Yamuna Expressway, Greater Noida. 3 BHK + 2T, 3 BHK + 3T, and Duplex Penthouses starting ₹1.30 Cr. Near Jewar Airport.",
    keywords: [
      "Elite X Yamuna Expressway",
      "Elite X Sector 22D",
      "Sector 22D Greater Noida",
      "Sector 22D Yamuna Expressway",
      "Sector 22D apartments",
      "Sector 22D properties",
      "Yamuna Expressway apartments",
      "Yamuna Expressway properties",
      "Yamuna Expressway flats",
      "Yamuna Expressway Sector 22D",
      "investment properties Noida",
      "investment Yamuna Expressway",
      "Eldeco Group projects",
      "Jewar Airport proximity",
      "Jewar Airport properties",
      "Greater Noida Yamuna Expressway",
      "Yamuna Expressway new projects",
      "Yamuna Expressway residential projects",
      "Yamuna Expressway luxury apartments",
      "Yamuna Expressway 3 BHK",
      "Yamuna Expressway penthouses",
      "Yamuna Expressway investment",
      "Yamuna Expressway real estate",
      "Sector 22D new launch",
      "Sector 22D investment",
      "Yamuna Expressway near Jewar Airport",
      "Yamuna Expressway Buddh Circuit",
    ],
    location: "Sector 22D, Yamuna Expressway, Greater Noida",
    developer: "Eldeco Group",
    reraId: "UPRERAPRJ752382",
    price: "₹1.30 Cr",
    unitTypes: ["3 BHK + 2T", "3 BHK + 3T", "Duplex Penthouses"],
    area: "1550-2800 sq.ft.",
    status: "New Launch",
    image: "/Elite X/hero.avif",
  },
  7: {
    slug: "ace-hanei",
    title: "ACE Hanei TechZone 4 - Luxury 3 & 4 BHK + Study",
    description:
      "ACE Hanei by Gaur Group + NBCC in Sector 1, TechZone 4, Greater Noida West. Luxury 3 & 4 BHK + Study apartments starting ₹2.50 Cr. NBCC execution, large apartment sizes.",
    keywords: [
      "ACE Hanei Greater Noida",
      "ACE Hanei TechZone 4",
      "TechZone 4 luxury apartments",
      "TechZone 4 Greater Noida",
      "TechZone 4 properties",
      "TechZone 4 Sector 1",
      "Gaur Group projects",
      "NBCC luxury projects",
      "NBCC TechZone 4",
      "large apartments Greater Noida",
      "large TechZone 4 apartments",
      "luxury TechZone 4",
      "Greater Noida TechZone luxury",
      "TechZone 4 3 BHK Study",
      "TechZone 4 4 BHK Study",
      "TechZone 4 large apartments",
      "TechZone 4 residential projects",
      "TechZone 4 property for sale",
      "TechZone 4 real estate",
      "Greater Noida West TechZone",
      "TechZone 4 low density",
      "Gaur Group TechZone",
      "NBCC TechZone luxury",
      "TechZone 4 premium homes",
    ],
    location: "Sector 1, TechZone 4, Greater Noida West",
    developer: "Gaur Group + NBCC",
    reraId: "UPRERAPRJ11256",
    price: "₹2.50 Cr",
    unitTypes: ["3 BHK + Study", "4 BHK + Study"],
    area: "2746-3862 sq.ft.",
    status: "Under Construction",
    image: "/ACE/hero.avif",
  },
  8: {
    slug: "the-brook-and-rivulet",
    title: "The Brook & Rivulet Sector 12 - Premium 3 & 4 BHK",
    description:
      "The Brook & Rivulet by Fusion Limited in Sector 12, Greater Noida West. Premium high-rise 3 & 4 BHK apartments starting ₹1.40 Cr. 3 side open corner plot, earthquake resistant.",
    keywords: [
      "Brook and Rivulet Greater Noida",
      "Brook and Rivulet Sector 12",
      "The Brook and Rivulet",
      "Sector 12 apartments",
      "Sector 12 Greater Noida",
      "Sector 12 Greater Noida West",
      "Sector 12 properties",
      "Fusion Limited projects",
      "high-rise apartments Noida",
      "high-rise Sector 12",
      "premium apartments Greater Noida West",
      "premium Sector 12 apartments",
      "Greater Noida West high-rise",
      "Sector 12 high-rise",
      "Sector 12 3 BHK",
      "Sector 12 4 BHK",
      "Sector 12 residential projects",
      "Sector 12 property for sale",
      "Sector 12 real estate",
      "Greater Noida West Sector 12",
      "Sector 12 corner plot",
      "Sector 12 MIVAN",
      "Fusion Limited Sector 12",
      "Sector 12 earthquake resistant",
    ],
    location: "Sector 12, Greater Noida West",
    developer: "Fusion Limited",
    reraId: "UPRERAPRJ535539",
    price: "₹1.40 Cr",
    unitTypes: ["3C", "3E", "4B", "4C"],
    area: "1350-2050 sq.ft.",
    status: "Under Construction",
    image: "/Brook and Rivulet/1.avif",
  },
  9: {
    slug: "renox-thrive",
    title: "Renox Thrive Sector 10 - Premium 3 & 4 BHK Residences",
    description:
      "Renox Thrive by Nivas Promoters (Renox Group) in Sector 10, Greater Noida West. Premium 3 & 4 BHK residences starting ₹1.42 Cr. Ethical practices, escalation free pricing.",
    keywords: [
      "Renox Thrive Greater Noida",
      "Renox Thrive Sector 10",
      "Sector 10 Greater Noida",
      "Sector 10 Greater Noida West",
      "Sector 10 apartments",
      "Sector 10 properties",
      "Renox Group projects",
      "premium residences Noida",
      "premium Sector 10 residences",
      "ethical real estate developers",
      "Greater Noida West Sector 10",
      "Sector 10 3 BHK",
      "Sector 10 4 BHK",
      "Sector 10 residential projects",
      "Sector 10 property for sale",
      "Sector 10 real estate",
      "Sector 10 escalation free",
      "Renox Group Sector 10",
      "Sector 10 premium homes",
      "Sector 10 transparent pricing",
      "Greater Noida West Sector 10",
    ],
    location: "Sector 10, Greater Noida West",
    developer: "Nivas Promoters (Renox Group)",
    reraId: "UPRERAPRJ742692",
    price: "₹1.42 Cr",
    unitTypes: ["3 BHK", "4 BHK"],
    area: "1582-2644 sq.ft.",
    status: "Under Construction",
    image: "/Renox/hero.avif",
  },
  10: {
    slug: "civitech-strings",
    title: "Civitech Strings Sector 12 - Premium 3 BHK + 3T",
    description:
      "Civitech Strings Tower Daytona by S.A.G. Realtech in Sector 12, Greater Noida West. Premium 3 BHK + 3T apartments starting ₹2.37 Cr. IGBC Gold rated, home automation.",
    keywords: [
      "Civitech Strings Greater Noida",
      "Civitech Strings Sector 12",
      "Tower Daytona",
      "Tower Daytona Sector 12",
      "Sector 12 Greater Noida",
      "Sector 12 apartments",
      "Civitech Group projects",
      "IGBC Gold rated apartments",
      "IGBC Gold Sector 12",
      "smart home apartments Noida",
      "smart home Sector 12",
      "Greater Noida West smart homes",
      "Sector 12 3 BHK 3T",
      "Sector 12 smart homes",
      "Sector 12 residential projects",
      "Sector 12 property for sale",
      "Sector 12 real estate",
      "Sector 12 IGBC Gold",
      "Sector 12 home automation",
      "Civitech Group Sector 12",
      "Sector 12 premium apartments",
      "Greater Noida West Sector 12",
    ],
    location: "Sector 12, Greater Noida West",
    developer: "S.A.G. Realtech (Civitech Group)",
    reraId: "UPRERAPRJ646272",
    price: "₹2.37 Cr",
    unitTypes: ["3 BHK + 3T"],
    area: "1975-2075 sq.ft.",
    status: "Under Construction",
    image: "/Civitech/hero.avif",
  },
  11: {
    slug: "forest-walk-villa",
    title: "Forest Walk Villa NH-24 Dasna - Luxury 4 BHK Villas",
    description:
      "Forest Walk Villa by Madhusudan Group / Yatharth Group in NH-24, Dasna, Ghaziabad. Luxury 4 BHK + 5T villas starting ₹2.85 Cr. 52 acres forest theme, 80% green landscape.",
    keywords: [
      "Forest Walk Villa Ghaziabad",
      "Forest Walk Villa NH24",
      "Forest Walk Villa NH-24",
      "NH24 villa",
      "NH24 villas",
      "NH24 properties",
      "NH-24 villa",
      "NH-24 villas",
      "NH-24 properties",
      "NH-24 Dasna villas",
      "NH-24 Dasna properties",
      "Dasna villas",
      "Dasna properties",
      "Dasna NH24",
      "luxury villas Ghaziabad",
      "luxury NH24 villas",
      "forest theme villas",
      "4 BHK villas Ghaziabad",
      "4 BHK NH24 villas",
      "Ghaziabad villas",
      "Ghaziabad properties",
      "NH24 real estate",
      "NH24 luxury villas",
      "NH24 residential projects",
      "NH24 new projects",
      "NH24 ready to move",
      "NH24 under construction",
      "NH24 investment properties",
      "NH24 premium villas",
      "NH24 4 BHK villas",
      "NH24 5 BHK villas",
      "NH24 fully furnished villas",
      "NH24 Vastu compliant villas",
      "NH24 forest living",
      "NH24 green villas",
      "NH24 luxury homes",
      "NH24 residential villas",
      "NH24 property for sale",
      "NH24 real estate projects",
    ],
    location: "NH-24, Dasna, Ghaziabad",
    developer: "Madhusudan Group / Yatharth Group",
    reraId: "UPRERAPRJ658961",
    price: "₹2.85 Cr",
    unitTypes: ["4 BHK + 5T Villas"],
    area: "3070-4200 sq.ft.",
    status: "Under Construction",
    image: "/ForestWalk/hero.avif",
  },
  12: {
    slug: "vvip",
    title: "VVIP Sector 12 - Luxury 3 & 4 BHK Residential",
    description:
      "VVIP by Vibhor Vaibhav Infrahome in Sector 12, Greater Noida West. Luxury 3 & 4 BHK apartments starting ₹2.40 Cr. Studio Symbiosis design, 70,000 sq.ft. clubhouse.",
    keywords: [
      "VVIP Greater Noida",
      "VVIP Sector 12",
      "Vibhor Vaibhav Infrahome",
      "Vibhor Vaibhav Sector 12",
      "Sector 12 Greater Noida",
      "Sector 12 Greater Noida West",
      "Sector 12 apartments",
      "luxury apartments Greater Noida West",
      "luxury Sector 12 apartments",
      "Studio Symbiosis design",
      "premium residential development",
      "Greater Noida West luxury",
      "Sector 12 3 BHK",
      "Sector 12 4 BHK",
      "Sector 12 residential projects",
      "Sector 12 property for sale",
      "Sector 12 real estate",
      "Sector 12 fully furnished",
      "Sector 12 clubhouse",
      "Vibhor Vaibhav Sector 12",
      "Sector 12 luxury homes",
      "Greater Noida West Sector 12",
    ],
    location: "Sector 12, Greater Noida West",
    developer: "Vibhor Vaibhav Infrahome Pvt. Ltd.",
    reraId: "UPRERAPRJ743225/10/2025",
    price: "₹2.40 Cr",
    unitTypes: ["3 BHK", "4 BHK"],
    area: "2000-3600 sq.ft.",
    status: "Under Construction",
    image: "/VVIP/hero.avif",
  },
  13: {
    slug: "panchsheel-greens-ii",
    title: "Panchsheel Greens-II Sector 16 - 2 & 3 BHK Ready to Move",
    description:
      "Panchsheel Greens-II by Panchsheel Group in Sector 16, Greater Noida West. Premium 2 & 3 BHK apartments starting ₹91.5 Lakhs. 26 acres, 65% open area, OC received. Ready to move.",
    keywords: [
      "Panchsheel Greens Greater Noida",
      "Panchsheel Greens Sector 16",
      "Panchsheel Greens II",
      "Sector 16 Greater Noida",
      "Sector 16 Greater Noida West",
      "Sector 16 apartments",
      "Sector 16 properties",
      "ready to move apartments",
      "ready to move Sector 16",
      "Panchsheel Group projects",
      "2 BHK ready to move",
      "2 BHK Sector 16",
      "3 BHK ready to move",
      "3 BHK Sector 16",
      "Greater Noida West ready to move",
      "Sector 16 ready to move",
      "Sector 16 2 BHK",
      "Sector 16 3 BHK",
      "Sector 16 residential projects",
      "Sector 16 property for sale",
      "Sector 16 real estate",
      "Sector 16 OC received",
      "Panchsheel Group Sector 16",
      "Sector 16 premium homes",
      "Greater Noida West Sector 16",
    ],
    location: "Sector 16, Greater Noida West",
    developer: "Panchsheel Group",
    reraId: "UPRERAPRJ8595",
    price: "₹91.5 Lakhs",
    unitTypes: ["2 BHK", "3 BHK"],
    area: "915-1525 sq.ft.",
    status: "Ready to Move",
    image: "/residential-plot-with-landscaping.avif",
  },
};

